### ISSUE TITLE
Test fails with v1.14.0

### ISSUE THREAD

**Issue by jdsika** [tezedge/tezedge#907]
```
error: test failed, to rerun pass '-p tezos_interop --test bootstrap_storage_protocol_v1_test'

Caused by:
  process didn't exit successfully: `/home/it-tezos/tezedge/target/release/deps/bootstrap_storage_protocol_v1_test-a42ce6ec30b8881f` (signal: 4, SIGILL: illegal instruction)
```

**Comment by jdsika** [comment]
```
LD_LIBRARY_PATH=./tezos/sys/lib_tezos/artifacts cargo run --release --bin light-node -- --config-file ../configs/tezedge.config
warning: /home/it-tezos/tezedge/storage/Cargo.toml: version requirement `0.5.3+zstd.1.4.5` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
    Finished release [optimized] target(s) in 0.35s
     Running `target/release/light-node --config-file ../configs/tezedge.config`
thread 'main' panicked at 'Failed to launch protocol runner: SocketTimeout', light_node/src/main.rs:118:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by jdsika** [comment]
Config [here](https://github.com/tezedge/tezedge/issues/852#issuecomment-987838649)

**Comment by tizoc** [comment]
Hello @jdsika, can you tell me about about your setup? (CPU, operating system, etc, output from `cat /proc/cpuinfo` would be great).

I suspect the problem you are seeing is related to https://github.com/supranational/blst/issues/10 (which would happen if your CPU doesn't support ADX).

**Comment by jdsika** [comment]
Here is my [cpu.log](https://github.com/tezedge/tezedge/files/7780168/cpu.log)

**Comment by tizoc** [comment]
@jdsika ok, I see there is no ADX, confirming that the issue is what I mentioned. Octez provides alternative binaries that don't require ADX, we will probably need to do the same. I need to investigate how, because the requirement comes from one of the cryptographic libraries.

**Comment by jdsika** [comment]
Thanks, so I will wait for the next release. I mean the server is not THAAT old. I think they should be supported...

**Comment by tizoc** [comment]
@jdsika hello, can you try rebuilding tezedge from the `no-adx` branch to see if that makes any difference ?

**Comment by jdsika** [comment]
```
Running tests/bootstrap_storage_protocol_v1_test.rs (target/release/deps/bootstrap_storage_protocol_v1_test-a42ce6ec30b8881f)

running 8 tests
error: test failed, to rerun pass '-p tezos_interop --test bootstrap_storage_protocol_v1_test'

Caused by:
  process didn't exit successfully: `/home/it-tezos/tezedge/target/release/deps/bootstrap_storage_protocol_v1_test-a42ce6ec30b8881f` (signal: 4, SIGILL: illegal instruction)

```

**Comment by jdsika** [comment]
```
Finished release [optimized] target(s) in 3m 54s
     Running `target/release/light-node --config-file ../configs/tezedge.config`
thread 'main' panicked at 'Failed to launch protocol runner: SocketTimeout', light_node/src/main.rs:118:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


To avoid the issue that I am doing something wrong:

```
git fetch origin
git checkout -b no-adx
git clean -dxf
SODIUM_USE_PKG_CONFIG=1 cargo build --release
SODIUM_USE_PKG_CONFIG=1 cargo test --release
LD_LIBRARY_PATH=./tezos/sys/lib_tezos/artifacts cargo run --release --bin light-node -- --config-file ../configs/tezedge.config

```

**Comment by tizoc** [comment]
@jdsika hmmm, try to `touch tezos/sys/build.rs` before running `cargo build` just to make sure that the build process will re-download the libtezos binary, it is possible that it didn't pick up the change in the dependency.

**Comment by jdsika** [comment]
btw my newer server does not support ADX as well ... [specs](https://ark.intel.com/content/www/de/de/ark/products/64610/intel-xeon-processor-e52450l-20m-cache-1-80-ghz-8-00-gts-intel-qpi.html)

**Comment by jdsika** [comment]
Paranoid mode:

```
rm -rf tezedge
git clone https://github.com/tezedge/tezedge
cd tezedge
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)" 
opam switch remove for_tezos
opam update
git checkout -b no-adx
touch tezos/sys/build.rs
SODIUM_USE_PKG_CONFIG=1 cargo build --release
SODIUM_USE_PKG_CONFIG=1 cargo test --release
```


-> Fail

**Comment by tizoc** [comment]
@jdsika there is no need to do any of those opam related steps, just rebuilding from that branch of the tezedge repository (and `touch tezos/sys/build.rs` as a safeguard).

I just pushed another version with another build of libtezos. I am following the same steps Octez is using to produce the ADX-less version, and although it makes blst not use such instructions, something else is still producing those instructions (although it is possible that such functions are not called from anywhere so it isn't an issue). It is a bit complicated because this code comes from the end of the chain of dependencies, and right now I don't have a server where I can properly test it.

Please give it another try and let me know if it works this time.

**Comment by jdsika** [comment]
We are one step closer. But running the node results in a creash - I did not delete the storage from the previous attempt to sync with < v1.14.0

```
LD_LIBRARY_PATH=./tezos/sys/lib_tezos/artifacts cargo run --release --bin light-node -- --config-file ../configs/tezedge.config
warning: /home/it-tezos/tezedge/storage/Cargo.toml: version requirement `0.5.3+zstd.1.4.5` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
WARN rustc_metadata::locator no metadata found: failed to mmap file '/home/it-tezos/tezedge/target/release/deps/libdarling_macro-4e2d40ab9ba300cf.so': memory map must have a non-zero length
    Finished release [optimized] target(s) in 0.33s
     Running `target/release/light-node --config-file ../configs/tezedge.config`
thread 'main' panicked at 'Context was not initialized successfully, so cannot continue, reason: InitializeContextOneshotResultCallbackError { reason: "Failed to initialize context because of protocol error, reason: Protocol error: OCaml storage init error: OCaml storage init failed, message: [{\"kind\":\"permanent\",\"id\":\"ffi.call_exception\",\"description\":\"Tezos_tezedge_context.Errors.RustFailure(\\\"LockDatabaseError { reason: AlreadyLocked { path: \\\\\\\"/home/it-tezos/.tezedge-data/context/lock\\\\\\\", pid: \\\\\\\"1417195\\\\\\\", self_pid: \\\\\\\"1418822\\\\\\\" } }\\\"): LockDatabaseError { reason: AlreadyLocked { path: \\\"/home/it-tezos/.tezedge-data/context/lock\\\", pid: \\\"1417195\\\", self_pid: \\\"1418822\\\" } }\"}]!" }', light_node/src/main.rs:190:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 29 16:31:07.834 WARN Failed to intialize context and continue feeding chain to protocol, reason: ProtocolServiceError { reason: ProtocolError { reason: OcamlStorageInitError { reason: InitializeError { message: "[{\"kind\":\"permanent\",\"id\":\"ffi.call_exception\",\"description\":\"Tezos_tezedge_context.Errors.RustFailure(\\\"LockDatabaseError { reason: AlreadyLocked { path: \\\\\\\"/home/it-tezos/.tezedge-data/context/lock\\\\\\\", pid: \\\\\\\"1417195\\\\\\\", self_pid: \\\\\\\"1418822\\\\\\\" } }\\\"): LockDatabaseError { reason: AlreadyLocked { path: \\\"/home/it-tezos/.tezedge-data/context/lock\\\", pid: \\\"1417195\\\", self_pid: \\\"1418822\\\" } }\"}]" } } } }
```

**Comment by tizoc** [comment]
Ok, that is good to know.

Regarding the storage, it depends on which backend you are using for the context database. If you are using the "irmin" (default) backend, no. But if you are using the "tezedge" backend (which seems to be the case from the errors), then yes because it is still on preview mode and the format has not been fully stabilized (once it has been stabilized there will be a migration command).

But your error is about the lock file, do you happen to have other tezedge (or `protocol-runner`) processes running? No more than a single instance can open the the context database at the same time. Check with `ps aux | grep protocol-runner` and `ps aux | grep light-node`.

In any case, if you want to use the "tezedge" backend for the context, yes, you will need to delete the storage created from the previous attempt using an older version and start again.

**Comment by jdsika** [comment]
There have been rogue processes indeed.  I did:
`kill -3 NUMBERS`

Then I removed all the storage folders and I am resycing:

```
curl localhost:18732/monitor/bootstrapped
{"block":"BLockGenesisGenesisGenesisGenesisGenesisf79b5d1CoW2","timestamp":"2018-06-30T16:07:32Z"}
```

There seem to be issues with connecting to peers. What are the default nodes to bootstrap from?

**Comment by tizoc** [comment]
These (which are the same as Octez):

https://github.com/tezedge/tezedge/blob/b8e20d9886ad8b6876ad62375bacf1f6b7999e3b/tezos/api/src/environment.rs#L221-L223

It may take some time for it to start, because the block headers are randomly obtained, and block application cannot start until the data for the first blocks has been obtained. But if you give it some time it should start to apply blocks once enough data has been fetched from other peers.
